# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75e70a2db21e57668807af33eadbe7aac5d9bb11d3aa29f28aff824a9405340c479d8edfaff79d030b3af80dabc072320d0594c179c86a86fee5c32909cddfd8

test:
  secret_key_base: 37c68e81d1a741dd022e2989eb4ec1e33c95f3adb310a0ad12609a816ab08eed105a0d6c4a9cce169ba5f6f4fabbb1ebaaaade3c33b0f34152fd0a3c99a28aaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
